name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        # run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build docker image
        run: docker build -t nguyentientai/class_ci-cd .
      - name: Publish image to docker hub
        run: docker push nguyentientai/class_ci-cd:latest
        
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Pull image from docker hub
        run: docker pull nguyentientai/class_ci-cd:latest
      - name: Delete old container
        run: docker rm -f class_ci-cd
      - name: Run docker container
        run: docker run -d -p 5005:5005 --name class_ci-cd nguyentientai/class_ci-cd